sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fahriulucay1/docker-travis-test -f Dockerfile.dev .

script:
  - docker run -e CI=true fahriulucay1/docker-travis-test npm run test
