sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fahriulucay1/docker-travis-test -f Dockerfile.dev .

script:
  - docker run -e CI=true fahriulucay1/docker-travis-test npm run test

deploy:
  provider: elasticbeanstalk
  refion: "us-east-2"
  app: "docker-travis-react"
  env: "DockerTravisReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-118076648593"
  bucket_path: "docker-travis-react"
  on:
    branch: master
  access_key_id: $AWS_AccessKey
  secret_access_key:
    secure: "$AWS_SecretKey"